name: conventional-commits
on:
  pull_request:
    types: [opened, reopened, synchronize, edited, ready_for_review]
jobs:
  main:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
